#!/usr/bin/env python3

import helpers
import sys
import os

from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv)!=2:
        print("Usage: ./tweets @screen_name")
    tweets = helpers.get_user_timeline(sys.argv[1].lstrip("@"))

    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    if tweets == [] :
        print("nothing to do with this")
    # analyze twitter
    for tweet in tweets:
        score=analyzer.analyze(tweet)
         # print sentiment
        if score > 0.0:
            print(score,colored(tweet, "green"))
        elif score < 0.0:
            print(score,colored(tweet, "red"))
        else:
            print(score,colored(tweet, "yellow"))
            
        
if __name__=="__main__":
    main()